# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            James Baker
tagline:          'bits and bobs'
description:      'A simple repository for ideas, snippets and opinions.'
url:              http://jbaker.io

author:
  name:           'James Baker'
  url:            https://www.github.com/j-baker

paginate:         5

# Custom vars
version:          1.0.0

# github:
#  repo:           https://github.com/poole/lanyon
