# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            James Baker
tagline:          'bits and bobs'
description:      'Ramblings of a young, naïve and inexperienced computer scientist/software engineer.'
url:              http://jbaker.io

author:
  name:           'James Baker'
  url:            https://www.github.com/j-baker

paginate:         5

# Custom vars
version:          1.0.0

# github:
repo:           https://github.com/j-baker/j-baker.github.io

exclude:        ['KudosPlease']